name: Deploy Portfolio via FTP

on:
  push:
    branches:
      - master

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git fetch --depth=2
        echo "Setup complete."

    - name: Get Changed Files
      id: get-changes
      run: |
        git diff --name-only HEAD~1 HEAD > changes.txt
        echo "::set-output name=changed_files::$(cat changes.txt | tr '\n' ' ')"

    - name: Deploy files via FTP
      if: steps.get-changes.outputs.changed_files != ''
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ # Répertoire local
        server-dir: /htdocs/ # Répertoire distant
        port: 21
        protocol: ftp
        exclude: "**/*" # Exclure tout par défaut
        include: "${{ steps.get-changes.outputs.changed_files }}" # Inclure uniquement les fichiers modifiés ou ajoutés
